### ISSUE TITLE
BallonPanelView – support for iframes

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#108]
First issue: BallonPanelView getAbsoluteRect() will fail with an element or range from a different frame.

The typical case – iframed editor. The function does now:

```js
	if ( elementOrRangeOrRect instanceof HTMLElement || elementOrRangeOrRect instanceof Range ) {
```

which will be always false.

But this is just the tip of an iceberg. There's whole topic about positioning according to an iframe to be resolved. It may be worth exposing all this as a util, btw (there's a ticket for that AFAIR).

**Comment by oleq** [comment]
`BPView` has not been designed to work with iframes in the first place. So the actual issue is: "allow `BPView` in an iframe environment". I'm sure this issue is but a fraction of what needs to be done.

**Comment by Reinmar** [comment]
Yeah, I realised that a minute later. Of course this is a bigger topic.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/125.
