### ISSUE TITLE
Bring EditorUI (controller) back

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui-default#109]
There are some reasons to have editor UI controller class:
 - some methods and properties like `_createEditableUIView`, `get editableElement()`, `featureComponents` does not belong to the view, they could be moved to the `Editor` main controller, but then it would handle too much,
 - engine bring its controllers, so UI could do it too, it would create a nice separation where there are separated controllers to handle engine and UI and the main `Editor` class only bind these pieces together,
 - the editor API for plugins should be well defined, so every developer should know what classes/properties should be brought to make plugins works fine with his editor. The `View` should not be a part of such API, so `featureComponents` should be defined in a better place.

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-ui-default/issues/119.
