### ISSUE TITLE
Configurable dropdown panel placement

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#115]
I need to create a dropdown with panel attached to the right side of the button:

![screenshot 2016-11-14 16 46 17](https://cloud.githubusercontent.com/assets/1057056/20271096/e8f308ea-aa89-11e6-9a28-2efd850632ef.png)

Question is: Do we want to add an option to `DropdownView` interface for that? Or should I do it locally in CSS for this single case?

**Comment by oskarwrobel** [comment]
When panel position will automatically adjust to available viewport then this option might be unnecessary.

**Comment by oleq** [comment]
I think we could start with a view attribute to control this behavior. I would manipulate the class, i.e. adding `.dropdown-menu-right` like in Bootstrap. 

Then, if needed, as a second step, some kind of heuristics could be implemented to make the positioning smarter when space is limited. But this is a bigger topic, which also concerns refactoring of the `BalloonPanelView`, which is  https://github.com/ckeditor/ckeditor5-ui-default/issues/98. The algorithm to position elements in a smart way should become a public utility.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/123.
