### ISSUE TITLE
Bring back EditorUI "controller"

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui-default#119]
A follow-up of https://github.com/ckeditor/ckeditor5-ui/issues/103.

Well described in https://github.com/ckeditor/ckeditor5-ui-default/issues/109.

**Comment by oleq** [comment]
Sub–issues:
- https://github.com/ckeditor/ckeditor5-core/issues/43
- https://github.com/ckeditor/ckeditor5-editor-classic/issues/38
- https://github.com/ckeditor/ckeditor5-link/issues/70

**Comment by oleq** [comment]
Duplicate of https://github.com/ckeditor/ckeditor5-ui-default/issues/109.

**Comment by Reinmar** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-ui-default/pull/121.
