### ISSUE TITLE
BallonPanel - invalid position when body has margin

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5-ui-default#126]
Position of BallonPanel is invalid:

![image](https://cloud.githubusercontent.com/assets/2270764/20557999/4d6417c0-b16e-11e6-8218-bf29600abcd0.png)

Steps to reproduce:

1. Go to https://ckeditor5.github.io/.
2. Open Web Inspector and find the `body` element.
3. Set styles for `element.style`: `margin-left: 400px;`
4. Click on "4th developer preview".
5. Position of BallonPanel is invalid.

When you set `padding-left` instead `margin-left`, all works fine.

![image](https://cloud.githubusercontent.com/assets/2270764/20558048/8efb613e-b16e-11e6-8eab-6f160711607e.png)

**Comment by oleq** [comment]
I checked this out and it breaks with any kind of CSS margin.
