### ISSUE TITLE
BalloonPanel dissapears when selecting text inside with mouse ends outside of it

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor5-ui-default#132]
When selecting text with mouse, to the end of the input field, and when releasing mouse button haging cursor outside the balloon panel - it dissapears.

![cke5_link_balloon](https://cloud.githubusercontent.com/assets/422571/20751864/82cd1f2a-b6fe-11e6-86bc-4557e87cf00b.gif)

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/122.
