### ISSUE TITLE
Avoid tooltip on editable

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-ui-default#133]
When moving the mouse over the editable, we have the "Rich Text Editor, whatever" message displayed in a tooltip. This is disturbing.

This tooltip has been inherited from CKEditor 4, where we use the `title` attribute in the editor because of a11y. It's high-time for us to finally get rid of this.

Firstly, we already duplicate the title with the aria-label attribute, which alone should be enough for a11y purposes.

Second, we still didn't work on a11y in CKEditor 5, so if this thing will have to be dealt, we'll figure out a solution for it later.

I propose to simply remove [this one line](https://github.com/ckeditor/ckeditor5-ui-default/blob/89c28ce84d93d1e4cd01cf8f529737b13d30706a/src/editableui/inline/inlineeditableuiview.js#L47) from the code and forget about it.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/121.
