### ISSUE TITLE
API for disabling Button tooltip

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#147]
Looks like it is not possible to disable tooltip for button with label https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/button/buttonview.js#L205-L215
Label is a default tooltip value when there is no title and this is OK for buttons with icon only.
We can improve this function to prevent of returning label as tooltip value for buttons with label, but I think there still should be an option to simply disable or enable tooltip.

**Comment by oskarwrobel** [comment]
I know it is possible to disable tooltip via CSS, but I'm not sure if CSS should provide such an API. If we decide to refactor tooltips using balloon panel then CSS API won't work.

**Comment by oleq** [comment]
Will be closed by https://github.com/ckeditor/ckeditor5-ui/issues/119.
