### ISSUE TITLE
Tooltips should not be displayed in the link balloon panel

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui-default#148]
A follow-up of #62.

![image](https://cloud.githubusercontent.com/assets/1099479/21420133/23c1a35e-c82c-11e6-8225-f2cab0736b41.png)

**Comment by oleq** [comment]
Related issue https://github.com/ckeditor/ckeditor5-ui-default/issues/147

**Comment by Reinmar** [comment]
Why has this balloon overflow:hidden?

**Comment by oskarwrobel** [comment]
The same problem was with titles (before tooltips). title was a duplicated label.

**Comment by oleq** [comment]
> Why has this balloon overflow:hidden?

It's not the point, @Reinmar. At least, not in this issue. The point is that a button with label should not have an automated tooltip that duplicates its label.

**Comment by Reinmar** [comment]
I know. I just wanted to know why there's overflow:hidden before opening a ticket for this. But I can open a new ticket if you don't want to discuss this here :P

**Comment by oleq** [comment]
## Do we need `ButtonView#title`?

`ButtonView` has the following attributes:

1. `#title` – if set, is used as a tooltip text, otherwise ignored,
2. `#label` – if set and `#withText == true`, it is displayed to the user as text of the button, otherwise ignored,
3. `#keystroke` – when `#title == undefined`, it is used to create a tooltip `#label (#keystroke)`

We made a smooth transition from `title` attribute to the tooltip, which is wrong, because default system titles aren't intrusive and remain always CSS–independent (i.e. not cropped by `overflow`).

What I think we need to do is to separate the (mostly future) accessibility layer from the UX layer (tooltips). While a11y is what must be always enabled, the UX layer should be configurable, e.g. tooltips should not be generated and displayed by default; they should be an extra feature:

### Example 1

```js
{
    label: 'Bold',
    // Keystroke without a tooltip does not make sense. It could be removed from here.
    keystroke: 'CTRL+B'
}
```

```html
<!-- There will be no tooltip in this case. -->
<button class="ck-button ck-tooltip_s ck-enabled ck-off" type="button">
    <an icon />
    <!-- The label available to screen readers. -->
    <span class="ck-button__label" aria-hidden="false">Bold</span>
</button>
```

### Example 2

```js
{
    label: 'Bold',
    keystroke: 'CTRL+B',
    withText: true
}
```

```html
<!-- Label will be visible to the user but there will be no tooltip in this case. -->
<button class="ck-button ck-button_with-text ck-tooltip_s ck-enabled ck-off" type="button">
    <an icon />
    <!-- The label available to screen readers. -->
    <span class="ck-button__label" aria-hidden="false">Bold</span>
</button>
```

### Example 3

```js
{
    label: 'Bold',
    keystroke: 'CTRL+B',
    tooltip: true
}
```

```html
<!-- Tooltip is auto–generated from #label and #keystroke -->
<button class="ck-button ck-tooltip_s ck-enabled ck-off" type="button" data-ck-tooltip="Bold (⌘B)">
    <an icon />
    <!--The label available to screen readers. -->
    <span class="ck-button__label" aria-hidden="false">Bold</span>
</button>
```

### Example 4

```js
{
    label: 'Bold',
    keystroke: 'CTRL+B',
    // `keystroke` available here should be what `getEnvKeystrokeText` has returned.
    tooltip: ( label, keystroke ) => `This button will do stuff if you press ${ keystroke }`
}
```

```html
<!-- Tooltip is a custom string -->
<button data-ck-tooltip="This button will do stuff if you press ⌘B" class="ck-button ck-tooltip_s ck-enabled ck-off" type="button" >
    <an icon />
    <!-- The label available to screen readers. -->
    <span class="ck-button__label" aria-hidden="false">Bold</span>
</button>
```

WDYT?

**Comment by oskarwrobel** [comment]
We need a keystroke as separate property because we need to parse it by a `getEnvKeystrokeText`? This looks like a key reason of this issue. 

For me this is ok:
```javascript
{
    label: 'Bold',
    tooltip: `Bold ${ getEnvKeystrokeText( 'CTRL+B' ) }`
}
```

If we know that toolbar is a place with similar buttons (Icon only + tooltip with keystroke) we can create a separate view or helper with label, icon and keystroke properties.

**Comment by Reinmar** [comment]
Guys, whatever you decide, just please remember that the `t()` function must be used in all these cases.

**Comment by oleq** [comment]
> Guys, whatever you decide, just please remember that the t() function must be used in all these cases.

I think the following API:

```js
const button = new ButtonView( locale );

button.isEnabled = true;
button.label = t( 'Link' );
button.icon = 'link';
button.keystroke = 'CTRL+K';

// label is already parsed by t(), and keystroke by getEnvKeystrokeText()
// The final string is: 
//    'A custom tooltip for "Link" with a handy keystroke "⌘K"'
// or
//    'Podpowiedź dla "Odnośnik" z pomocnym skrótem klawiaturowym "⌘K"'
button.tooltip = `${ t( 'A custom tooltip for' ) } "${ label }" ${ t( 'with a handy keystroke' ) } "${ keystroke }"`;
```

is enough. Right?

**Comment by oleq** [comment]
Self-review: no, it's not. I must re–think it.

**Comment by fredck** [comment]
Leaving a proposal for the overall approach to part of the problem (in priority order):

 * Focus is Accessibility:
    * `title`: if it matches the Tooltip approach and purpose.
    * `innerText` if there is an inner visual label (that will never be hidden) that works for a11y.
    * `innerText with aria-hidden=false` if there is an inner visual label (that may be hidden) that works for a11y.
    * `aria-label`

* Focus is Tooltip:
   * Custom Tooltip:
      * `aria-label` if it also fulfills the accessibility purpose.
      * `data-ck-tooltip` if it doesn't match the accessibility purpose.
    * Default Browser Tooltip:
       * `title`

In our case, as we'll be implementing custom tooltips there were we need them, we would never use `title` then.

**Comment by pjasiun** [comment]
I did not follow the discussion, so sorry if you already mentioned it, but, based on the issue title: what with the contextual toolbar which for sure should have tooltips?

**Comment by oleq** [comment]
> I did not follow the discussion, so sorry if you already mentioned it, but, based on the issue title: what with the contextual toolbar which for sure should have tooltips?

You should have followed it ;-)

**Comment by oleq** [comment]
I'm for the following approach, any comments?

```js
const button = new ButtonView( locale );

button.label = t( 'Link' );
button.keystroke = 'CTRL+K';

// 'Link (⌘K)'
button.tooltip = true;

// 'A custom tooltip for "Link" with a handy keystroke "⌘K"'
button.tooltip = ( label, keystroke ) => 
	`${ t( 'A custom tooltip for' ) } "${ label }" ${ t( 'with a handy keystroke' ) } "${ keystroke }"`;
```

**Comment by Reinmar** [comment]
Just one – `Ctrl+K` as we discussed somewhere :P

**Comment by oleq** [comment]
Will be closed in https://github.com/ckeditor/ckeditor5-ui/issues/119.
