### ISSUE TITLE
Tooltips of disabled buttons have transparency

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-ui-default#151]
Disabled toolbar buttons have semi-transparent tooltips:

![image](https://cloud.githubusercontent.com/assets/630060/26155528/c285715a-3b13-11e7-8b7e-6f396da6e513.png)

Tooltips should look the same no matter the state of the button.

**Comment by oleq** [comment]
For one thing, this repository is dead. And it's a duplicate of https://github.com/ckeditor/ckeditor5-theme-lark/issues/70 anyway.
