### ISSUE TITLE
Dropdown changes width when switching between the options

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui-default#28]
It is undesired because other items of the toolbar change their position.

![image](https://cloud.githubusercontent.com/assets/1099479/16588251/9d72e930-42ce-11e6-8a82-2fc8971428ec.png)

Dropdown should have an optional numeric `model#width` attribute to constrain the width. `text-overflow: ellipsis` could be used to handle long button labels. It should probably be implemented in `DropdownButton` class.

**Comment by Reinmar** [comment]
Hm... do you think that we could automate this somehow? Like guessing the needed width? OTOH, I can't imagine making any reasonable guess – text can have different letters (lots of narrow ones), font can be changed, etc.

**Comment by oleq** [comment]
> Like guessing the needed width?

If someone configures an option in the dropdown named _"My lovely pink on yellow that contrasts with the wallpaper in my mother's bathroom"_, then what? Allow dropdown which consumes 70% of horizontal space in the toolbar because of this option? Calculate some average? What if all options are lengthy? I don't think this is the good use-case for any heuristics. When developer decides to use a dropdown they need to estimate the width to keep it simple.

**Comment by fredck** [comment]
I would go with a default enforced by CSS and overridable through the model properties. This would make it easier to customize the size by simple CSS definitions.

**Comment by oleq** [comment]
I decided to go the easy way and fix label width with CSS as there's no known use–case for dynamic dropdown width at the moment.

Besides, if we go with model–controlled dropdown width, the problem gets complicated because the width will be set on the dropdown (button) but the actual truncation happens in the label (child of the button), which is **not** 100% width of the dropdown. To make it work, some maths might be required.
