### ISSUE TITLE
Implement rich button tooltips with keystroke information

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui-default#62]
A followup of https://github.com/ckeditor/ckeditor5-ui-default/issues/29.

Related issue: https://github.com/ckeditor/ckeditor5-ui-default/issues/58.

---
#29 implements tooltips using the `title` attribute, but they're not very pretty. They could look like this instead:

![image](https://cloud.githubusercontent.com/assets/1099479/18121272/16241da6-6f64-11e6-9510-0897c3687e7f.png)

I wonder if pure CSS solution is enough here using `::after`/`::before` pseudo–elements and `content: attr(title)` definition. This approach feels a way more lightweight than any JS solution and lets us postpone `BalloonPanel` [refactoring](https://github.com/ckeditor/ckeditor5-ui-default/issues/58), which is a good news 😄 .

**Comment by oleq** [comment]
A random example from the web http://cssdeck.com/labs/pure-css-tooltip-with-arrow.

**Comment by fredck** [comment]
The only problem with the CSS only approach is that the title attribute still has its UI behavior, which duplicates the tooltip.

Also, being it a balloon, wouldn't it be nicer to have it at the top of the button?

**Comment by fredck** [comment]
> The only problem with the CSS only approach is that the title attribute still has its UI behavior, which duplicates the tooltip.

I the other hand, I was wondering if we really need the title attribute here or we can instead use aria attributes for the a11y requirements. It seems to be the way to go.

**Comment by fredck** [comment]
In fact, I've just updated the [above example](http://cssdeck.com/labs/pure-css-tooltip-with-arrow), replacing `title` with `aria-label` and it works like a charm.

**Comment by oleq** [comment]
> Also, being it a balloon, wouldn't it be nicer to have it at the top of the button? 

Why not. TBH I haven't done any UX research yet about such stuff.

> In fact, I've just updated the above example, replacing title with aria-label and it works like a charm.

👍

**Comment by Reinmar** [comment]
Important question in this topic. Do we want to be able to display rich info in those tooltips? By rich, I mean enhanced with HTML+CSS.

In the buttons case when we only need to display the title and the keystroke it doesn't sound like something crucial, though it would be nice to mark the keystroke with a bit different color e.g.

However, if we'll ever plan to display some bigger infos, then we'd need enhanced tooltips. And I think that if we go with pure CSS now, then in the future we may need a more advanced solution anyway, duplicating a bit what we have. This should be transparent for the users of the button component, even if we change the tooltip type, but perhaps it's worth consideration.

OTOH, a CSS approach is a couple of hours of work max, while a new component is ~2 days. So perhaps this is the answer.

**Comment by fredck** [comment]
Sounds like overengineering. Let's keep it simple and efficient, as proposed. I doubt more than that will bring effective value. Anyway, having this discussed here is not a bad thing.

**Comment by pjasiun** [comment]
It might be useful to be able to tell where tooltip should be shown: above, below, on the left or on the right. For instance for the inline toolbar, if the toolbar is above the text, not to hide the content, we may consider showing tooltip above the button as well. Or if we will have a horizontal menu tooltips should not hide other buttons and should be next to them.

**Comment by oleq** [comment]
The very first problem with a pure `:after`/`:before` solution: the tooltip remains when hovered, making the content beneath inaccessible:

![dec-19-2016 18-20-49](https://cloud.githubusercontent.com/assets/1099479/21322096/ebeb74fc-c617-11e6-8c9b-46a53e0faea1.gif)

**Comment by Reinmar** [comment]
:(

**Comment by oleq** [comment]
It could work if we move it a couple of px off the button, but... not always. 

![dec-19-2016 18-27-01](https://cloud.githubusercontent.com/assets/1099479/21322297/c6369bfa-c618-11e6-8665-b8c08d33ced1.gif)

**Comment by Comandeer** [comment]
That issue could be resolved using `pointer-events: none` → https://jsfiddle.net/h63Lbpth/

**Comment by Reinmar** [comment]
LOL, I thought about it but I thought that it only affects JS events :D. @Comandeer for the rescue!

**Comment by oleq** [comment]
@Comandeer You're the Gandalf.
