### ISSUE TITLE
Higher z-index for sticky toolbar

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#63]
There is a collision between sticky toolbar and toolbar from other editor instance.

![sticku toolbar](https://cloud.githubusercontent.com/assets/1057056/18123922/5c63e402-6f70-11e6-8ad1-493ea6339f8f.gif)

**Comment by fredck** [comment]
That's because of the issue reported here: https://github.com/ckeditor/ckeditor5-ui/issues/66

**Comment by oskarwrobel** [comment]
Right. This problem will disappear when we fix **Issue2** from https://github.com/ckeditor/ckeditor5-ui/issues/66.
Thanks.
