### ISSUE TITLE
Some of protected methods don't have to be protected

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#64]
I've spotted and talked about it with @oleq, that some of methods are `@protected` instead of `@private` only to be testable. Here is an example of such a [method](https://github.com/ckeditor/ckeditor5-ui-default/blob/master/src/dropdown/dropdown.js#L47-L51) and [test](https://github.com/ckeditor/ckeditor5-ui-default/blob/master/tests/dropdown/dropdown.js#L44). But this method is not even called in test, the method name is only used as `describe()` title and class constructor executes it. So there is no reason to mark this method as protected, it could be confusing.

**Comment by Reinmar** [comment]
Most of the time we should default to that, because once we make something public (and protected methods are public for child classes) it's hard to touch it. OTOH, we need to keep extensibility in our minds, so there are exceptions from this rule.

**Comment by oleq** [comment]
I agree that mentioned methods should become `@private` as in https://github.com/ckeditor/ckeditor5-design/wiki/Code-Style#visibility-levels. But still I'm for keeping them as class methods for granularity and clarity of what happens in what order.

As for tests, `constructor` test should only check whether `_createButton` and `_createPanel` are called and then, each method should be called and tested separately.

**Comment by oskarwrobel** [comment]
> But still I'm for keeping them as class methods for granularity and clarity of what happens in what order.

Me too.

> As for tests, constructor test should only check whether _createButton and _createPanel are called and then, each method should be called and tested separately.

Then methods need to be `@protected` at least.

Anyway... right now we have some protected methods to make them testable, but we test them as a private.

**Comment by oleq** [comment]
> Then methods need to be @protected at least.

A good point. Huh. Let's make them `@private` then and test `constructor` only.

**Comment by Reinmar** [comment]
I guess this is outdated now. Since a list of all issues wasn't compiled and we refactored the whole lib I'm closing this.
