### ISSUE TITLE
Why does BalloonPanelView have couple of public methods?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#70]
This looks very weird:

``` js

    /**
     * Returns balloon visibility state.
     *
     * See {@link ui.balloonPanel.BalloonPanelViewModel#isVisible}.
     *
     * @returns {Boolean}
     */
    get isVisible() {
        return this.model.isVisible;
    }

    /**
     * Shows the balloon panel.
     *
     * See {@link ui.balloonPanel.BalloonPanelViewModel#isVisible}.
     */
    show() {
        this.model.isVisible = true;
    }

    /**
     * Hides the balloon panel.
     *
     * See {@link ui.balloonPanel.BalloonPanelViewModel#isVisible}.
     */
    hide() {
        this.model.isVisible = false;
    }
```

Why are those needed if they are just proxies to the model?

The only problem I have is with `attachTo()`, because I'm unsure how we could pass it through the model. But... stay tuned, because @pjasiun raised another valid concern about this.

**Comment by Reinmar** [comment]
The promised issue: https://github.com/ckeditor/ckeditor5-ui/issues/73

**Comment by oskarwrobel** [comment]
As @oleq wrote in one of the comments: https://github.com/ckeditor/ckeditor5-ui-default/pull/60#discussion_r77628332 

> show()/hide() are nothing but syntax sugar here.

**Comment by Reinmar** [comment]
That only strengthens arguments for ckeditor/ckeditor5-ui#73 :D. If we need such syntax sugar, then what's the point of the separated model?

**Comment by fredck** [comment]
Just shooting... observability?

**Comment by Reinmar** [comment]
We can make the view observable as well.

**Comment by oskarwrobel** [comment]
I also thought about making view observable and them model will be not necessary.

**Comment by oleq** [comment]
The `View` class used to be observable a long, long time ago :P We switched to VM approach to define a clear, uniform interface for each view class, i.e. to provide easy interchangeability. See my comment in https://github.com/ckeditor/ckeditor5-ui/issues/73#issuecomment-246607891.

**Comment by fredck** [comment]
I would find it weird to have the view observable instead of its model.

**Comment by Reinmar** [comment]
Moved to https://github.com/ckeditor/ckeditor5-ui/issues/128.
