### ISSUE TITLE
cke-editor vs ck-editor in boxededitoruiview

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-ui-default#71]
You can find both as the class name:

`cke-editor*`:
https://github.com/ckeditor/ckeditor5-ui-default/blob/d4a6ee75e5ef50317fd0637c86c6b79a61522eeb/src/editorui/boxed/boxededitoruiview.js#L48-L49

`ck-editor*`:
https://github.com/ckeditor/ckeditor5-ui-default/blob/d4a6ee75e5ef50317fd0637c86c6b79a61522eeb/src/editorui/boxed/boxededitoruiview.js#L59

Is there any reasone to use both? Shouldn't we have it written somewhere in the code style docs?

**Comment by oleq** [comment]
Issue split into https://github.com/ckeditor/ckeditor5-ui/issues/112 and https://github.com/ckeditor/ckeditor5-ui-default/issues/124.
