### ISSUE TITLE
BalloonPanel appears in place where is not enough space

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#76]
![position](https://cloud.githubusercontent.com/assets/1057056/18630609/feb86b22-7e6d-11e6-962a-6d975834a09f.gif)

And see: https://github.com/ckeditor/ckeditor5-link/issues/33

**Comment by fredck** [comment]
The placement position should not care about the placement of balloon relatively to the editable rectangle but instead to the viewport only.

**Comment by oleq** [comment]
> The placement position should not care about the placement of balloon relatively to the editable rectangle but instead to the viewport only.

Not exactly, @fredck. 

The algorithm should make sure that:
1. the balloon is visible in the viewport (missing part) 
2. the balloon is as much within the area of editable as possible (already implemented) – to prevent from sticking on the left/right side of the editor and avoid covering the toolbar.

**Comment by Reinmar** [comment]
In FF it always opens like this: 

<img width="975" alt="screen shot 2016-09-22 at 11 59 26" src="https://cloud.githubusercontent.com/assets/156149/18744013/3077ea8e-80bc-11e6-8343-22c80d2da778.png">

**Comment by oleq** [comment]
@Reinmar It's a link–specific issue, that one https://github.com/ckeditor/ckeditor5-link/issues/37.

**Comment by oskarwrobel** [comment]
> the balloon is as much within the area of editable as possible (already implemented) – to prevent from sticking on the left/right side of the editor and avoid covering the toolbar.

This approach is fine in most cases, but lets keep in mind that it has some dead ends.

![image](https://cloud.githubusercontent.com/assets/1057056/18790674/0010c952-81b0-11e6-8aa3-11fdaac10f7a.png)
