### ISSUE TITLE
Stop listening scroll event when it is not necessary - sticky toolbar

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#80]
FollowUp of https://github.com/ckeditor/ckeditor5-ui-default/issues/74
See: https://github.com/ckeditor/ckeditor5-ui-default/pull/75#discussion_r79584396

**Comment by oleq** [comment]
More or less a duplicate of https://github.com/ckeditor/ckeditor5-ui-default/issues/14.
