### ISSUE TITLE
The click and esc handlers expect a controller, but they need a DOMEmitter

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#89]
They've been added in https://github.com/ckeditor/ckeditor5-ui-default/pull/88 and https://github.com/ckeditor/ckeditor5-ui-default/pull/86.

The `options.controller` option was unclear, so for now I changed it to `ui.Controller`. However, its description correctly said (before my changes) that in fact `ui.DomEmitter` is expected.

It's a bit unfortunate – we can either change this option to `options.view` and expect `ui.View` which implements `ui.DomEmitter` or mix `DomEmitter` to `controller`. I think that the first option is cleaner, but I've started thinking that in general it may be confusing that you can't listen using `controller.listenTo` to DOM events. One may expect that... and there will be a surprise.

So we can go either way. WDYT, @oskarwrobel?

**Comment by oskarwrobel** [comment]
I'm for changing to `option.view`. For me it's hard to imagine controller wihout view which has to listen to DOM event.

**Comment by oleq** [comment]
The new syntax brought in https://github.com/ckeditor/ckeditor5-ui-default/pull/120 dramatically simplified the usage, i.e.

```js
escPressHandler( {
	emitter: balloonPanelView,
	activator: () => balloonPanelView.isVisible,
	callback: () => this._hidePanel( true )
} );
```

vs. old one

```js
escPressHandler( {
	controller: balloonPanelView,
	emitter: balloonPanelView,
	model: balloonPanelView,
	activeIf: 'isVisible',
	callback: () => this._hidePanel( true )
} );
```

and also given that there's no `Controller` class anymore, I consider this issue fixed.
